version: '3'
services: 
  frontend:
    build: 
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports: 
     - 3000:3000
    volumes:
      - type: bind
        source: ./data
        target: /app/public/png
    # environment:
    #   - IMAGE_DIR=images
  backend:
    build: 
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports: 
     - "9000:9000"
  pytorch:
    build:
      dockerfile: ../../docker/python/Dockerfile
      context: ./python/pytorch_server
    ports:
      - 5000:5000
  db: 
    image: postgres:15.4
    environment:
        # Local development only.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
