apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bookmarkit
  name: bookmarkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarkit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bookmarkit
    spec:
      containers:
      - image: frontend
        name: frontend
        resources: {}
status: {}
