# docker-compose to spin up postgres for Spring. For the project docker-compose 
# use ../docker-compose.yaml, to run/build the entire stack.
version: '3'
services:
  db: 
    image: postgres:15.4
    environment:
        # Local development only.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  # elastic: 
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
  #   environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']

  #   ports: 
  #     - 9200:9200

